---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: eda
version: 0.1.0
readme: README.md
authors:
  - John Barker (github.com/gundalow)
  - Doston Toirov (github.com/Dostonbek1)
description: null
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - infrastructure
  - tools
  - eda
repository: https://github.com/ansible-collections/community.eda
#documentation: https://github.com/ansible-collection-migration/community.eda/tree/main/docs
homepage: https://github.com/ansible-collections/community.eda
issues: https://github.com/ansible-collections/community.eda/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - .pre-commit-config.yaml
  - "*.tar.gz"
  - .ansible
  - .benchmarks
  - .config
  - .github
  - .gitleaks.toml
  - .idea
  - .mypy_cache
  - .pre-commit-config.yaml
  - .pytest_cache
  - .readthedocs.yaml
  - .ruff_cache
  - .tool-versions
  - .tox
  - .venv
  - .vscode
  - CHANGELOG.md
  - ansible_collections
  - changelogs/.plugin-cache.yaml
  - codecov.yml
  - collections
  - cspell.config.yaml
  - demos
  - docs/.changelog.yml
  - docs/.gitignore
  - docs/antsibull-docs.cfg
  - docs/build
  - docs/build.sh
  - docs/conf.py
  - docs/docsite
  - docs/rst
  - docs/temp-rst
  - pyproject.toml
  - run_pytest.yml
  - start_app.yml
  - tests/conftest.py
  - tests/integration/*
  - tests/run-staging
  - tests/unit
  - tox.ini
  - venv
